force-app/main/default/objects/MBExpense__c/MBExpense__c.object-meta.xml
<CustomObject>
    <label>MBExpense</label>
    <nameField>
        <displayFormat>MBEX-{0000}</displayFormat>
        <label>MBExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBExpenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBExpenseItem__c/MBExpenseItem__c.object-meta.xml
<CustomObject>
    <label>MBExpenseItem</label>
    <nameField>
        <displayFormat>MBEI-{00000}</displayFormat>
        <label>MBExpenseItem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBExpenseItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MBExpenseItem__c/fields/MBExpense__c.field-meta.xml
<CustomField>
    <fullName>MBExpense__c</fullName>
    <label>MBExpense</label>
    <referenceTo>MBExpense__c</referenceTo>
    <relationshipLabel>MBExpenseItems</relationshipLabel>
    <relationshipName>MBExpenseItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataController.cls
@isTest
private class TestDataController {
    @isTest
    static void importSampleData() {
        Test.startTest();
        DataController.importSampleData();
        Test.stopTest();

        Integer expensesNumber = [SELECT COUNT() FROM MBExpense__c];
        Integer expenseItemsNumber = [SELECT COUNT() FROM MBEXpenseItem__c];

        System.assert(expensesNumber > 0, 'Expected expenses were created.');
        System.assert(expenseItemsNumber > 0, 'Expected items were created.');
    }
}