force-app/main/default/objects/MBExpense__c/MBExpense__c.object-meta.xml
<CustomObject>
    <label>MBExpense</label>
    <nameField>
        <displayFormat>MBEX-{0000}</displayFormat>
        <label>MBExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBExpenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBExpense__c/fields/Expense_Claim_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Claim_Type__c</fullName>
    <label>Expense Claim Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Business</fullName>
            </value>
            <value>
                <fullName>Sales Conference</fullName>
            </value>
            <value>
                <fullName>COVID-19 Home Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MBExpense__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MBExpenseItem__c/MBExpenseItem__c.object-meta.xml
<CustomObject>
    <label>MBExpenseItem</label>
    <nameField>
        <displayFormat>MBEI-{00000}</displayFormat>
        <label>MBExpenseItem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBExpenseItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MBExpenseItem__c/fields/Expense_Item_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Item_Date__c</fullName>
    <label>Expense Item Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MBExpenseItem__c/fields/Expense_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Item_Type__c</fullName>
    <label>Expense Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accomodation</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Meals</fullName>
            </value>
            <value>
                <fullName>Office Supplies</fullName>
            </value>
            <value>
                <fullName>Subscriptions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MBExpenseItem__c/fields/MBExpense__c.field-meta.xml
<CustomField>
    <fullName>MBExpense__c</fullName>
    <label>MBExpense</label>
    <referenceTo>MBExpense__c</referenceTo>
    <relationshipLabel>MBExpenseItems</relationshipLabel>
    <relationshipName>MBExpenseItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MBExpenseItem__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
                <default>true</default>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MBExpenseItem__c/fields/Personal_Expense__c.field-meta.xml
<CustomField>
    <fullName>Personal_Expense__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personal Expense</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DataController.cls
public with sharing class DataController {
    @AuraEnabled
    public static void importSampleData() {
        delete [SELECT Id FROM MBExpense__c];
        delete [SELECT Id FROM MBEXpenseItem__c];
/*insert*/
        insertMBExpenses();
    }

    private static void insertMBExpenses() {
        List<MBExpense__c> mbexpenses = new List<MBExpense__c>();
        MBExpense__c mbexpense = new MBExpense__c();
        mbexpense.Expense_Date__c = Date.today();
        mbexpense.Expense_Claim_Type__c = 'General Business';
        mbexpense.Status__c = 'New';
        mbexpense.Comments__c = 'my expense comments';
        insert mbexpense;

        MBExpenseItem__c mbexpenseitem = new MBExpenseItem__c();
        mbexpenseitem.MBExpense__c = mbexpense.id;
        mbexpenseitem.Amount__c = 100;
        mbexpenseitem.payment_method__c = 'Credit Card';
        mbexpenseitem.personal_expense__c = false;
        mbexpenseitem.expense_item_type__c = 'Meals';
        mbexpenseitem.expense_item_date__c = Date.today().addDays(-2);
        mbexpenseitem.Comments__c = 'meals item comment';

        insert mbexpenseitem;

        mbexpenseitem = new MBExpenseItem__c();
        mbexpenseitem.MBExpense__c = mbexpense.id;
        mbexpenseitem.Amount__c = 200;
        mbexpenseitem.payment_method__c = 'Credit Card';
        mbexpenseitem.personal_expense__c = false;
        mbexpenseitem.expense_item_type__c = 'Travel';
        mbexpenseitem.expense_item_date__c = Date.today().addDays(-3);
        mbexpenseitem.Comments__c = 'travel item comment';
        insert mbexpenseitem;

        mbexpenseitem = new MBExpenseItem__c();
        mbexpenseitem.MBExpense__c = mbexpense.id;
        mbexpenseitem.Amount__c = 12.99;
        mbexpenseitem.payment_method__c = 'Credit Card';
        mbexpenseitem.personal_expense__c = true;
        mbexpenseitem.expense_item_type__c = 'Office Supplies';
        mbexpenseitem.expense_item_date__c = Date.today().addDays(-4);
        mbexpenseitem.Comments__c = 'personal item comment';

        insert mbexpenseitem;
    }
}